version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: periconecta_postgres
    restart: always
    environment:
      POSTGRES_DB: periconecta_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - periconecta_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: periconecta_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@periconecta.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - periconecta_network

volumes:
  postgres_data:

networks:
  periconecta_network:
    driver: bridge